spring:
  application:
    name=weather-forecast
  jackson:
    serialization:
      indent_output:
        true
weatherapi:
  key: 3ff872cd78a841df9c7132440241806
  url: https://api.weatherapi.com/v1


