spring:
  application:
    name=weather-forecast
weatherapi:
  key: 3ff872cd78a841df9c7132440241806
  url: https://api.weatherapi.com/v1
springdoc:
  api-docs:
    path: "/docs/swagger"
  swagger-ui:
    path: "/swagger-ui-weather-forecast.html"
